[package]
name = "allup"
version = "0.0.0"
license = "Unlicense"
authors = ["Jonathan Cornaz"]
edition = "2021"
rust-version = "1.76"
repository = "https://github.com/jcornaz/allup"
description = "A CLI to check that all (configured) services are currently up"
categories = []
keywords = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
crossterm = { version = "0.27.0", default-features = false }
main_error = "0.1.2"
ratatui = "0.26.1"
reqwest = { version = "0.11.24", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.36", features = ["rt-multi-thread", "macros", "time"] }
toml = { version = "0.8.10", default-features = false, features = ["parse"] }
url = { version = "2.5", features = ["serde"] }

[dev-dependencies]

